[package]
name = "api-cpp"
version = "0.1.0"
authors = ["rust-vmm AWS maintainers <rust-vmm-maintainers@amazon.com>"]
edition = "2018"

[dependencies]
cxx = "1.0"

vmm = { path = "../vmm" }

[build-dependencies]
cxx-build = "1.0"
